import { createElement } from "@lwc/engine-dom";
import Demo10ParentCallingChildMethod from "c/demo10ParentCallingChildMethod";

describe("c-demo10-parent-calling-child-method", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-demo10-parent-calling-child-method", {
      is: Demo10ParentCallingChildMethod
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
