import { createElement } from "@lwc/engine-dom";
import Demo7PublicPropertiesContactList from "c/demo7PublicPropertiesContactList";

describe("c-demo7-public-properties-contact-list", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-demo7-public-properties-contact-list", {
      is: Demo7PublicPropertiesContactList
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
