import { createElement } from "@lwc/engine-dom";
import Demo12LifeCycleDemo from "c/demo12LifeCycleDemo";

describe("c-demo12-life-cycle-demo", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-demo12-life-cycle-demo", {
      is: Demo12LifeCycleDemo
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
