import { createElement } from "@lwc/engine-dom";
import Demo2ApplyingCSSParent from "c/demo2ApplyingCSSParent";

describe("c-demo2-applying-css-parent", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-demo2-applying-css-parent", {
      is: Demo2ApplyingCSSParent
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
